### ISSUE TITLE
Upgrade to sbt-precog 5.0.2

### ISSUE THREAD

**Issue by rintcius** [precog/qdata#310]
Part of https://github.com/precog/precog/issues/125

**Comment by rintcius** [comment]
Will also cleanup the repos. E.g. use of wartremover, slamdata predef, assembly plugin.

**Comment by alissapajer** [comment]
@rintcius regarding slamdata predef, was your plan to get rid of it in all v3 repos? That would be my preference.

**Comment by rintcius** [comment]
@alissapajer Yes, that's my preference too.

**Comment by alissapajer** [comment]
👍🏽 let's do it. Goodbyte slamdata predef.

**Comment by alissapajer** [comment]
> Goodbyte

Lol that's a great typo.

**Comment by alissapajer** [comment]
I probably type "byte" more than I type "bye"

**Comment by rintcius** [comment]
😄  
👋

**Comment by rintcius** [comment]
<2>

**Comment by rintcius** [comment]
<0>
